### ISSUE TITLE
docker-compose for local testing?

### ISSUE THREAD

**Issue by phildini** [pybee/beekeeper#12]
Since we're dependent on postgres _and_ django, and since the combs are docker-dependent, what do we think about setting up `docker-compose.yml` for local development?

If we (and I think here we might mean just @freakboy3742 😛 ) thinks this is an ok idea, I'll get this spun up.

**Comment by freakboy3742** [comment]
Absolutely +1 for this. We may need to do some refactoring to get the common startup logic and task handling out of the aws module, but this sounds awesome to me.

**Comment by phildini** [comment]
Oh, this is done.
