### ISSUE TITLE
Link to the correct issue page for feedback

### ISSUE THREAD

**Issue by Tadaboody** [pybee/beekeeper#23]
Right now every time @brutusthebee does anything I want to give feedback on, I'm never sure if it's an issue for pybee/beekeeper of pybee/beefore. (Even as I'm writing this, I'm not sure if it's more suited for beefore)

A link in @brutusthebee's bio or even in his comments will help clarify this confusion and streamline the feedback process

**Comment by freakboy3742** [comment]
I can't see any way to put links in a bio (if you've got any tips, I'm all ears) - in the meantime, I've expanded Brutus' bio. If you think it needs additional changes, let me know.

Regarding the specific query - the comments that Brutus leaves are always the result of feedback from Beefore, not BeeKeeper. BeeKeeper is the CI system that runs (amongst other things) Beefore tasks.
