### ISSUE TITLE
Docs link in README points to wrong project docs

### ISSUE THREAD

**Issue by timb07** [pybee/beekeeper#4]
The link to Read The Docs in the README points to documentation for https://github.com/haikuginger/beekeeper, not the BeeWare BeeKeeper project.

(I was wondering how Roy Fielding's REST API and HATEOAS principles applied to CI...)

**Comment by adamfast** [comment]
Discussed with Russ at DjangoCon, will be looking at during sprints.

**Comment by phildini** [comment]
Fixed in #5
